#!/bin/bash

ESPTOOL='python -m esptool'
SDK_ROOT=~/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589
VERSION=esp32.r1.eth

$ESPTOOL --chip esp32 merge_bin -o $VERSION.bin \
    --flash_mode dout \
    --flash_freq 40m \
    --flash_size 4MB \
    0x1000 $SDK_ROOT/tools/sdk/bin/bootloader_dout_40m.bin \
    0x8000 .pio/build/esp32dev/partitions.bin \
    0xe000 $SDK_ROOT/tools/partitions/boot_app0.bin \
    0x10000 .pio/build/esp32dev/firmware.bin
